[package]
name = "palimpsest-paas-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Kubernetes/CloudNativePG runtime renderer and reconciler for Palimpsest managed Postgres."
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "palimpsest-paas-runtime"
path = "src/main.rs"

[dependencies]
palimpsest-paas-core = { path = "../palimpsest-paas-core", version = "0.1.1" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_yaml = "0.9"
thiserror.workspace = true

[lints]
workspace = true
