[package]
name = "palimpsest-paas-control-plane"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Rust control-plane skeleton for Palimpsest PaaS."
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "palimpsest-paas-control-plane"
path = "src/main.rs"

[dependencies]
axum = { workspace = true, features = ["json", "query"] }
base64 = "0.22"
palimpsest-paas-core = { path = "../palimpsest-paas-core", version = "0.1.1" }
palimpsest-paas-runtime = { path = "../palimpsest-paas-runtime", version = "0.1.1" }
palimpsest-permissions = { path = "../../../crates/palimpsest-permissions", version = "0.1.1" }
palimpsest-sql = { path = "../../../crates/palimpsest-sql", version = "0.1.1" }
rcgen = "0.13"
ring = "0.17"
rustls = "0.23"
rustls-pemfile = "2"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "postgres", "json"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net", "time"] }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }

[lints]
workspace = true
