{{- if .Values.dbProxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "palimpsest-paas.fullname" . }}-db-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "palimpsest-paas.labels" . | nindent 4 }}
    app.kubernetes.io/component: db-proxy
spec:
  replicas: {{ .Values.dbProxy.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: db-proxy
  template:
    metadata:
      labels:
        {{- include "palimpsest-paas.labels" . | nindent 8 }}
        app.kubernetes.io/component: db-proxy
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: db-proxy
          image: "{{ .Values.dbProxy.image.repository }}:{{ .Values.dbProxy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.dbProxy.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          command:
            {{- toYaml .Values.dbProxy.command | nindent 12 }}
          ports:
            - name: postgres
              containerPort: {{ .Values.dbProxy.listenPort }}
          resources:
            {{- toYaml .Values.dbProxy.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "palimpsest-paas.fullname" . }}-db-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "palimpsest-paas.labels" . | nindent 4 }}
    app.kubernetes.io/component: db-proxy
spec:
  type: {{ .Values.dbProxy.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: db-proxy
  ports:
    - name: postgres
      port: {{ .Values.dbProxy.service.port }}
      targetPort: postgres
{{- end }}
