[package]
name = "palimpsest-sql"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "SQL parsing, validation, and MIR definitions for Palimpsest."
keywords.workspace = true
categories.workspace = true

[dependencies]
petgraph.workspace = true
sqlparser = { workspace = true, features = ["visitor"] }
thiserror.workspace = true

[dev-dependencies]
insta.workspace = true
proptest.workspace = true

[lints]
workspace = true
